### ISSUE TITLE
How to properly prepare a simulator build for upload

### ISSUE THREAD

**Issue by laurentsigal** [waldoapp/waldo-cli#5]
This is going to be critical if we support simulators.
Look into how appetize does it

**Comment by aminebellakrid** [comment]
For iOS, upload a .zip or .tar.gz file containing your compressed .app bundle

Your .app bundle must represent a simulator build of your app. Look in ~/Library/Developer/Xcode/DerivedData/<project-name>/Build/Products/Debug-iphonesimulator/

Alternatively, you may run xcodebuild -sdk iphonesimulator in your project directory, then zip the .app bundle in build/Release-iphonesimulator/

For Android, upload the .apk containing your app

After your app is built, either via Android Studio or by running the command ./gradlew assembleRelease in your project directory, look in <project-name>/<module-name>/build/outputs/apk/
